#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - dsixda (dislam@rocketmail.com)
#
# Android Kitchen is 100% free.  This script file is intended for personal
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################

version=0.224


if [ ! -e menu ]
then
  echo
  echo "确认你在安卓厨房的安装目录下执行该文件。否则在运行该脚本时"
  echo "会出现问题。你应该在使用”cd“命令跳转到”安卓厨房“的目录下"
  echo "之后，再使用”./menu“来运行”安卓厨房”                "
  exit 0
fi

dir_list=( original_update scripts tools )
error_found=0

for check_dir in ${dir_list[@]}
do
  if [ ! -e $check_dir ]
  then
    echo "错误：文件夹 '$check_dir' 未找到"
    error_found=1
  fi
done

if [ $error_found == 1 ]
then
  echo
  echo "请确保已经正确的放置了“安卓厨房”的文件夹。"
  exit 0
fi


chmod 755 scripts/*
scripts/check_install_dir

if [ "$?" == "1" ]
then
  exit 0
fi

scripts/init_kitchen
scripts/check_binaries

if [ "$?" == "1" ]
then
  exit 0
fi


while :
do

  clear

  echo 
  echo "============================================================"
  echo " 安卓厨房 版本号：$version - 作者 dsixda (xda-developers.com)"
  echo "                                        chaol汉化
  echo "============================================================"
  echo 
  echo "> 主菜单"
  echo
  echo "  1 - 从ROM中设立工作目录"
  echo "  2 - 添加root权限"
  echo "  3 - 加入BusyBox"
  echo "  4 - 禁止开机音效"
  echo "  5 - 对所有的apk文件进行”zip对齐“以优化内存使用"
  echo "  6 - 改变ROM的擦出状态"
  echo "  7 - 改变ROM的名称"
  echo "  8 - 显示工作目录信息"
  echo 
  echo "  0 - 高级选项"
  echo " 00 - 经典选项（废旧并且较少使用）"
  echo " 99 - 从工作目录构建ROM"
  echo
  echo "  u - 安卓厨房信息/更新/捐献"
  echo "  x - 退出"
  echo
  echo 
  echo -n "Enter option: "
  read opt

  if [ "$opt" != "x" ] && [ "$opt" != "u" ] && [ "$opt" != "1" ]
  then
    scripts/check_multiple_working
  fi
  
  if [ "$?" != "1" ]
  then
    case $opt in
      1) clear; scripts/check_rom; continue;;
      2) scripts/do_root; continue;;
      3) scripts/add_busybox show_help;;
      4) scripts/disable_sounds;;
      5) scripts/do_zipalign;;
      6) scripts/change_wipe;;
      7) scripts/change_rom_name;;
      8) scripts/show_rom_info;;
      0) scripts/menu_advanced $version; continue;;
      00) scripts/menu_legacy $version; continue;;
      99) scripts/build_rom;;
      u) scripts/about $version; continue;;
      x) scripts/init_kitchen; clear; echo; echo "再见^_^"; echo; exit 1;;
      *) echo "无效选项"; continue;;
    esac
  fi

  scripts/press_enter

done

